
package output;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthImpl", targetNamespace = "http://soap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthImpl {


    /**
     * 
     * @param authToken
     * @return
     *     returns output.Answer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://soap/", className = "output.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://soap/", className = "output.AuthResponse")
    @Action(input = "http://soap/AuthImpl/authRequest", output = "http://soap/AuthImpl/authResponse")
    public Answer auth(
        @WebParam(name = "authToken", targetNamespace = "")
        String authToken);

    /**
     * 
     * @param userId
     * @return
     *     returns output.Answer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeToken", targetNamespace = "http://soap/", className = "output.MakeToken")
    @ResponseWrapper(localName = "makeTokenResponse", targetNamespace = "http://soap/", className = "output.MakeTokenResponse")
    @Action(input = "http://soap/AuthImpl/makeTokenRequest", output = "http://soap/AuthImpl/makeTokenResponse")
    public Answer makeToken(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @param refreshToken
     * @return
     *     returns output.Answer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refresh", targetNamespace = "http://soap/", className = "output.Refresh")
    @ResponseWrapper(localName = "refreshResponse", targetNamespace = "http://soap/", className = "output.RefreshResponse")
    @Action(input = "http://soap/AuthImpl/refreshRequest", output = "http://soap/AuthImpl/refreshResponse")
    public Answer refresh(
        @WebParam(name = "refreshToken", targetNamespace = "")
        String refreshToken);

    /**
     * 
     * @param userId
     * @return
     *     returns output.Answer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://soap/", className = "output.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://soap/", className = "output.LogoutResponse")
    @Action(input = "http://soap/AuthImpl/logoutRequest", output = "http://soap/AuthImpl/logoutResponse")
    public Answer logout(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

}
